### ISSUE TITLE
Sistema de Reputação e Validação de Dados

### ISSUE THREAD

**Issue by uira** [PROCERGS/login-cidadao#180]
Verificar sistema de medalhas e validação de dados, usado no mapas culturais, para equalizar com a política do LC;

**Comment by decko** [comment]
Seus problemas se acabaram-se.
http://openbadges.org

Existe uma issue pra criação de badges lá no MC? Rola de encontrar ela lá pra gente manter essas issues linkadas?

**Comment by guilhermednt** [comment]
A vibe do [Open Badges](http://openbadges.org) é outra.

Não sei se entendi o objetivo dessa issue. O Mapas já consegue acessar o LC de boa...
