### ISSUE TITLE
Build docker image to facilitate local development

### ISSUE THREAD

**Issue by lpirola** [PROCERGS/login-cidadao#246]
https://www.docker.com/toolbox
##

**Comment by guilhermednt** [comment]
Issue PROCERGS#726 got us closer to using docker and has a working `Dockerfile` but we still need to upgrade to _Symfony 3_ before being able to actually use Docker fully.

With _Symfony 2_ is near impossible to create an actual Docker Image.

**Comment by guilhermednt** [comment]
Não depende de mim... Os mantenedores dos Bundles que nós dependemos (inclusive o que implementa OIDC) é que sabem. Se eles não suportam Symfony > 2.8, não adianta querer atualizar que não vai funcionar...
