### ISSUE TITLE
Botão para cópia de chaves do App

### ISSUE THREAD

**Issue by nitaibezerra** [PROCERGS/login-cidadao#325]
Incluir botão para facilitar a cópia para área de transferência das chaves pública e privada na tela de administração de um Serviço/App.

Uma sugestão é este botão ficar ao lado do campo da chave gerada e ao clicar ele copia o valor para a área de transferência.

**Comment by guilhermednt** [comment]
Isso já existe. :)

**Comment by nitaibezerra** [comment]
Boaaa!! Bora atualizar logo esse brinquedo no MinC!

2015-12-25 15:51 GMT-02:00 Guilherme Donato <notifications@github.com>:

> Isso já existe. :)
>
> Sent from my iPhone
>
> > On 25 de dez de 2015, at 14:06, Nitai Bezerra da Silva <
