### ISSUE TITLE
add a confirmation password field to the new user form

### ISSUE THREAD

**Issue by robertkapa** [PROCERGS/login-cidadao#350]
Currently, new users are registered setting name, email and password. It is necessary a redundant password field to force users pain attention to this field. In background, the application can check if both field match and accept or refuse the password.
![captura de tela de 2016-02-11 20 32 02](https://cloud.githubusercontent.com/assets/641411/12993023/eb41f72e-d0fe-11e5-9751-65795f38c022.png)

**Comment by guilhermednt** [comment]
I'm fine with it, but I think we should then remove the phone field to keep it short.

**Comment by robertkapa** [comment]
That seems ok! But the phone number work to a kind of confirmation, no? I mean: how useful is the phone number? I'm fine about remove it anyway.

**Comment by guilhermednt** [comment]
@robertkapa currently it's pretty useless. At PROCERGS we don't have access to an SMS Gateway to do anything useful with it. We had hope to be able to send SMS but I, personally, gave up already... :disappointed:

**Comment by robertkapa** [comment]
ok! So, in that form, to keep short, could be the fields email, password e re-type password, right? (3 field, as currently) Sounds good for me.
