### ISSUE TITLE
Public and Private Keys for Client and id_token

### ISSUE THREAD

**Issue by timothyjeffcoat** [PROCERGS/login-cidadao#403]
I hate to ask a question in the "issues" section but I see no other way.

The question is in regards to the LoginCidadao\OpenIDBundle\Storage\PublicKey class use.

Am I correct in reading the code that the id_token is being encoded via the Private Key?

If so then the Public Key will be used decode or decrypt?

My understanding is that we are supposed to encrypt with Public and decrypt with Private.  Is this not correct?

**Comment by guilhermednt** [comment]
Hi @timothyjeffcoat 

I'm not sure where that is happening, but I suppose that this would be done to ensure the id_token was issued by the private key holder.

Could you point to a specific line of code?

**Comment by timothyjeffcoat** [comment]
If you look at LoginCidadao\OpenIDBundle\ResponseType\IdToken.php line 31 

    protected function encodeToken(array $token, $client_id = null)
    {
        $private_key = $this->publicKeyStorage->getPrivateKey($client_id);
        $algorithm   = $this->publicKeyStorage->getEncryptionAlgorithm($client_id);

        $token['kid'] = 'pub';

        return $this->encryptionUtil->encode($token, $private_key, $algorithm);
    }

The use of the getPrivateKey.

I expected to see getPublicKey instead.

I am asking out of curiosity.

**Comment by guilhermednt** [comment]
Thanks, @timothyjeffcoat 

I actually just extended `OAuth2\OpenID\ResponseType\IdToken` to add the key id to the token. But I think this is done to sort of "sign" the token.
