### ISSUE TITLE
Make email confirmation required

### ISSUE THREAD

**Issue by guilhermednt** [PROCERGS/login-cidadao#408]
`login-cidadao` instances should be able to configure whether or not they want mandatory email validation.

**Comment by uira** [comment]
Isso significa que quem não confirmar o email não vai ter acesso ao sistema?

**Comment by guilhermednt** [comment]
Basicamente isso, @uira. A ideia é solicitar a confirmação do email oferecendo oportunidade de editar o email cadastrado.

**Comment by guilhermednt** [comment]
Depends on redelivre#44

**Comment by guilhermednt** [comment]
Implemented by #413 (redelivre#44)

**Comment by uira** [comment]
Isso, obviamente, pode ser opcional, ativado ou desativado, no painel do superadmin, é isso?!

**Comment by guilhermednt** [comment]
Não, @uira. É um parâmetro.

``` yaml
require_email_validation: true
```
