### ISSUE TITLE
Tornar as Estatísticas Públicas

### ISSUE THREAD

**Issue by uira** [PROCERGS/login-cidadao#578]
https://logincidadao.rs.gov.br/statistics/

Essa página poderia estar pública, sem nenhum prejuízo à segurança ou privacidade.

Pelo contrário, pode ser um indicador de confiança e segurança. Um provedor usado por muita gente, e que muita gente tem o CPF confirmado, bem, esse provedor é mais seguro do que outro provedor vazio.

**Comment by guilhermednt** [comment]
Besides, I think we could have an endpoint with this data. This way it will be possible to aggregate stats about all known instances!
