### ISSUE TITLE
Inserir identidade para fazer pedido de LAI

### ISSUE THREAD

**Issue by gabrielacaesar** [PROCERGS/login-cidadao#750]
Boa tarde.

Sou jornalista e trabalho em São Paulo. Estou tentando fazer um pedido de LAI ao governo do Rio Grande do Sul. Para fazer o pedido, o sistema pede que eu complete as informações. Numa das etapas, ele solicita o meu documento de identidade. O campo "estado" fica bloqueado em "Rio Grande do Sul". Meu RG é expedido pelo Rio de Janeiro. O site não me permite alterar o estado. Cliquei em "pular etapa", mas a página apenas recarrega. Eu não consigo acessar a próxima etapa. Inclusive, acho um pouco demais que o site exija o meu RG sendo que até o meu CPF eu já informei. O E-Sic da CGU, por exemplo, não pede RG.

Como usuária que faz o primeiro acesso ao site, também tive alguma dificuldade em descobrir o processo para fazer uma solicitação de LAI. Eu tive que "ativar" o serviço para ele aparecer na minha conta. 

Estou à disposição.

Um abraço,
Gabriela

**Comment by guilhermednt** [comment]
Boa tarde, Gabriela

Essa restrição e o comportamento que você está observando vem da [Central de Informação](http://www.centraldeinformacao.rs.gov.br/), que aparentemente exige um RG do RS. Não tenho muito conhecimento das regras de negócio desse serviço, mas suponho que isso seja um bug.

Quando você clicou em "pular" a Central de Informação não poderia simplesmente te redirecionar de volta para o Login Cidadão. Eles deveriam, ao menos, explicar o motivo desse redirect e, idealmente, fornecer um campo próprio para que você preencha o RG diretamente na Central de Informação sem compartilhar esse dado com o Login Cidadão. Por isso eu acredito que seja um bug.

Para o Login Cidadão, o único campo obrigatório é o email e isso ocorre basicamente para permitir que os usuários recuperem a senha em caso de esquecimento.

Sugiro contato com a equipe da Central de Informação para que eles possam analisar a situação com maior brevidade e responder com mais propriedade: http://www.centraldeinformacao.rs.gov.br/fale-conosco

No momento estou em férias, então não tenho nem como encaminhar internamente, por isso o melhor seria tentar contato com eles diretamente, através do site.
