### ISSUE TITLE
Omnibox de Serviços

### ISSUE THREAD

**Issue by uira** [PROCERGS/login-cidadao#92]
Integrar, à barra do MEU RS, um INPUT estilo campo de busca, que fará busca em sites, serviços e informações do governo, previamente cadastrados ou captados por crawler que a gente faça pra rastrear o *.rs.gov.br.

Funcionalidade e comportamento parecidos com o do facebook. 

Que acham?

**Comment by uira** [comment]
Pq fechou?
Em 06/01/2015 11:11, "lordvacilaoerrocerto" <notifications@github.com>
escreveu:

**Comment by uira** [comment]
Reabrindo essa issue, pra gente verificar a integração com o Serviços.gov.br.

Assim como no padrão google, acho que a gente pode investir na barra Integradora do Login Cidadão, que tem basicamente uma busca.

**Comment by guilhermednt** [comment]
Acho que isso é um projeto maior. Precisaria de uma instalação estadual de um ElasticSearch da vida.
