### ISSUE TITLE
Informações dinâmicas na Home do MEU RS

### ISSUE THREAD

**Issue by uira** [PROCERGS/login-cidadao#94]
Precisamos incluir um campo de Edição do HTML que fica na caixa da home, ao lado do bloco de cadastro.

Vamos precisar trocar o conteúdo dessa área quase todos os dias, e isso precisa ser melhor gerenciado.

Há uma interface de administrador, onde pode ser incluído esse campo.

**Comment by guilhermednt** [comment]
Simplicidade é tudo. Vamos deixar direto ao ponto como está agora até que uma nova necessidade apareça.
